services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOCAL_URL=http://api:8000/items
    command: [ "/bin/bash", "-c", "uv run flake app tests && uv run pytest tests/item_tests.py"]
